name: "mobileclip_s0_image_pipeline"
platform: "ensemble"
max_batch_size: 64
input [
  {
    name: "IMAGE_PATH"
    data_type: TYPE_STRING
    dims: [ 1 ]
  },
  {
    name: "CROP_X"
    data_type: TYPE_INT64
    dims: [ 1 ]
    optional: true
  },
  {
    name: "CROP_Y"
    data_type: TYPE_INT64
    dims: [ 1 ]
    optional: true
  },
  {
    name: "CROP_WIDTH"
    data_type: TYPE_INT64
    dims: [ 1 ]
    optional: true
  },
  {
    name: "CROP_HEIGHT"
    data_type: TYPE_INT64
    dims: [ 1 ]
    optional: true
  }
]
output [
  {
    name: "embeddings"
    data_type: TYPE_FP32
    dims: [ 512 ]
  }
]
ensemble_scheduling {
  step [
    {
      model_name: "mobileclip_s0_image_preprocessing"
      model_version: -1
      input_map { key: "IMAGE_PATH" value: "IMAGE_PATH" }
      input_map { key: "CROP_X" value: "CROP_X" }
      input_map { key: "CROP_Y" value: "CROP_Y" }
      input_map { key: "CROP_WIDTH" value: "CROP_WIDTH" }
      input_map { key: "CROP_HEIGHT" value: "CROP_HEIGHT" }
      output_map { key: "images" value: "preprocessed_images" }
    },
    {
      model_name: "mobileclip_s0_image_backend"
      model_version: -1
      input_map { key: "images" value: "preprocessed_images" }
      output_map { key: "embeddings" value: "raw_embeddings" }
    },
    {
      model_name: "mobileclip_s0_l2norm"
      model_version: -1
      input_map { key: "raw_embeddings" value: "raw_embeddings" }
      output_map { key: "embeddings" value: "embeddings" }
    }
  ]
}
