{
 "title": "Triton Inference Server",
 "description": "Dashboard for Triton inference server",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "Model",
    "label": "Model",
    "query": {
     "query": "label_values(nv_inference_request_success,model)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Triton Memory Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (job)(nv_pinned_memory_pool_total_bytes)",
     "legendFormat": "{{job}} - Total memory"
    },
    {
     "expr": "max by (job)(nv_pinned_memory_pool_used_bytes)",
     "legendFormat": "{{job}} - Used memory"
    }
   ]
  },
  {
   "title": "Pending requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (job,model)(nv_inference_pending_request_count{model=~\"$Model\"})",
     "legendFormat": "{{job}} - {{model}}"
    }
   ]
  },
  {
   "title": "Inference request rate",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (job,model)(irate(nv_inference_request_success{model=~\"$Model\"}[1m]))\n",
     "legendFormat": "{{job}} - {{model}} - success"
    },
    {
     "expr": "max by (job,model)(irate(nv_inference_request_failure{model=~\"$Model\"}[1m]))\n",
     "legendFormat": "{{job}} - {{model}} - failure"
    }
   ]
  },
  {
   "title": "Model inference rate",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (job,model)(irate(nv_inference_count{model=~\"$Model\"}[1m]))\n",
     "legendFormat": "{{job}} - {{model}}"
    }
   ]
  },
  {
   "title": "Inference request duration",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max by (job,model)(irate(nv_inference_request_duration_us{model=~\"$Model\"}[1m]))\n",
     "legendFormat": "{{job}} - {{model}}"
    }
   ]
  },
  {
   "title": "Inference queue duration",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max by (job,model)(irate(nv_inference_queue_duration_us{model=~\"$Model\"}[1m]))\n",
     "legendFormat": "{{job}} - {{model}}"
    }
   ]
  },
  {
   "title": "Compute input duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max by (job,model)(irate(nv_inference_compute_input_duration_us{model=~\"$Model\"}[1m]))\n",
     "legendFormat": "{{job}} - {{model}}"
    }
   ]
  },
  {
   "title": "Compute inference duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max by (job,model)(irate(nv_inference_compute_infer_duration_us{model=~\"$Model\"}[1m]))\n",
     "legendFormat": "{{job}} - {{model}}"
    }
   ]
  },
  {
   "title": "Compute output duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max by (job,model)(irate(nv_inference_compute_output_duration_us{model=~\"$Model\"}[1m]))",
     "legendFormat": "{{job}} - {{model}}"
    }
   ]
  }
 ]
}