name: "mobileclip_s0_l2norm"
backend: "python"
max_batch_size: 256
dynamic_batching { }
input [
  {
    name: "raw_embeddings"
    data_type: TYPE_FP32
    dims: [ 512 ]
  }
]
output [
  {
    name: "embeddings"
    data_type: TYPE_FP32
    dims: [ 512 ]
  }
]
